### ISSUE TITLE
Error in 0.0.12 when executing update-accounts

### ISSUE THREAD

**Issue by tstroband** [OlafConijn/AwsOrganizationFormation#16]
```ERROR: unexpected error occurred...
TypeError: matches is not iterable
    at CfnTemplate._resolveOrganizationFunctions (/usr/local/lib/node_modules/aws-organization-formation/dist/src/cfn-binder/cfn-template.js:155:45)
    at CfnTemplate._resolveOrganizationFunctions (/usr/local/lib/node_modules/aws-organization-formation/dist/src/cfn-binder/cfn-template.js:182:42)
    at CfnTemplate._resolveOrganizationFunctions (/usr/local/lib/node_modules/aws-organization-formation/dist/src/cfn-binder/cfn-template.js:182:42)
    at CfnTemplate.resolveOrganizationFunctions (/usr/local/lib/node_modules/aws-organization-formation/dist/src/cfn-binder/cfn-template.js:62:46)
    at new CfnTemplate (/usr/local/lib/node_modules/aws-organization-formation/dist/src/cfn-binder/cfn-template.js:33:14)
    at CloudFormationBinder.enumBindings (/usr/local/lib/node_modules/aws-organization-formation/dist/src/cfn-binder/cfn-binder.js:35:33)
    at CloudFormationBinder.enumTasks (/usr/local/lib/node_modules/aws-organization-formation/dist/src/cfn-binder/cfn-binder.js:63:36)
    at HandleErrors (/usr/local/lib/node_modules/aws-organization-formation/dist/index.js:71:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by tstroband** [comment]
References the following fragment:

```
} else if (key === 'Fn::Sub') {
   if (typeof val === 'string') {
      let result = val;
      const matches = val.match(/\${([\w\.]*)}/g);
      for (const match of matches) {
         const expresion = match.substr(2, match.length - 3); // ${xxx}
```

Possibly caused by no match, in which case the `val.match` returns `null` (which is not iterable)
Either should be:
```
const matches = val.match(/\${([\w\.]*)}/g) | [];
```
which will return an array or, in the case of no match, an empty array.

Or could be:
```
const matches = val.matchAll(/\${([\w\.]*)}/g);
```

which will always return an `iterable`.

**Comment by OlafConijn** [comment]
fixed
